In [21]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Python is a popular programming language widely used in various fields, from scientific computations to data analysis, thanks to its extensive library support. When working in these domains, it is often necessary to perform effective operations on large datasets, carry out mathematical computations, and manipulate data quickly. This is where NumPy comes into play.

NumPy is a Python library created with the abbreviation "Numerical Python." It is a fundamental tool for scientific computations and data analysis. This library is particularly robust in dealing with multidimensional arrays and mathematical functions.

The article consists of a total of 11 sections:

1 ) NumPy - Importing NumPy Library

2 )NumPy - Why Numpy

3 )NumPy - Creating Numpy Arrays

4 )NumPy - NumPy Basics

5 )NumPy - NumPy Basics Operations

6 )NumPy - Index Selection

7 )NumPy - Fancy Indexing

8 )NumPy - Stacking Arrays

9 )NumPy - Splitting Arrays

10 )NumPy - Convert and Copy

11 )NumPy - Conditional Operations in NumPy

**1 ) NumPy - Importing NumPy Library**

In this section, which explains how to import the NumPy library and its usage with abbreviations, it demonstrates how methods like "import numpy as np" and "from numpy import *" are used.

In [22]:
import numpy as np # With this declaration, the numpy package will now be represented as 'np' within the program.

from numpy import * # With this declaration, all commands within the numpy package can be called directly.

**2 ) NumPy - Why Numpy**

In this section, information about the importance and advantages of NumPy is provided, along with an explanation of how NumPy can be used with a simple example.

In [23]:
import numpy as np
from numpy import *

a = [1 , 2 , 3 , 4 , 5]
b = [6 , 7 , 8 , 9 , 10]

ab = []

for i in range(0,len(a)):
    ab.append( a[i] * b[i] )

print("Using a for loop ==> " , ab)
# Output: Using a for loop ==> [6, 14, 24, 36, 50]

a = np.array([1 , 2 , 3 , 4 , 5])
b = np.array([6 , 7 , 8 , 9 , 10])

islem_2 = a * b

print("Using the NumPy library ==> " , islem_2)
# Output: Using the NumPy library ==> [ 6 14 24 36 50] 

Using a for loop ==>  [6, 14, 24, 36, 50]
Using the NumPy library ==>  [ 6 14 24 36 50]


**3 ) NumPy - Creating NumPy Arrays (NumPy Array'i Oluşturmak)**

In this section, different ways of creating arrays using NumPy are explained. It demonstrates how to create arrays consisting of zeros and random numbers.

In [24]:
import numpy as np
from numpy import *

array1 = np.array([1, 2, 3, 4, 5])

print(type(np.array([1, 2, 3, 4, 5])))
# Output:
# <class 'numpy.ndarray'>

print(np.zeros(10, dtype=int)) # Creating an array of zeros
# Output:
# [0 0 0 0 0 0 0 0 0 0]

print(np.random.randint(0, 10, size=10)) 
# Creating a random array with 10 elements between 0 and 10
# Output:
# [6 3 0 4 3 9 7 9 8 0]

print(np.random.normal(10, 4, (3, 4))) 
# Creating a 3x4 array with mean 10 and standard deviation 4
# Output:
# [[11.94853195 11.11021788 18.32516726  8.18730031] 
#  [ 7.09954823  9.11757558 11.23290031 10.23979572] 
#  [11.07443887  9.43310612  9.28065901  6.35797049]]

<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0]
[9 1 9 6 3 4 0 6 6 0]
[[18.6482233   6.93401184  6.73157728 12.41538054]
 [15.40043882  7.32577098  4.31443394  8.6947532 ]
 [ 6.9107728  15.45893037 12.77888212  6.14021148]]


**4 ) NumPy - NumPy Basics**

This section provides information about basic operations, dimensions, and data types in NumPy. It explains fundamental features such as array operations, the number of dimensions, data type, and size.

In [25]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array.shape)  # Output: (15,)

a = array.reshape(3,5)
print("shape =>", a.shape)  # Output: shape => (3, 5)

print("Dimension =>",a.ndim)  # Output: Dimension => 2

print("Data type =>" , a.dtype.name)  # Output: Data type => int32

print("Size => " , a.size)  # Output: Size =>  15

print("type => " ,type(a))  # Output: type =>  <class 'numpy.ndarray'> 

array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,8,7,5]])

matrix0 = np.zeros((3,4))
matrix0[0][0] = 5
print(matrix0)  # Output: [[5. 0. 0. 0.]
               #          [0. 0. 0. 0.]
               #          [0. 0. 0. 0.]]

matrix1 = np.ones((3,4))
print(matrix1)  # Output: [[1. 1. 1. 1.]
               #          [1. 1. 1. 1.]
               #          [1. 1. 1. 1.]]

matrix_ = np.empty((5,4))
print(matrix_)  # Output: Array with small numbers close to zero.

b = np.arange(0 , 90 , 12)
print("==> " , b)  # Output: ==>  [ 0 12 24 36 48 60 72 84]

c = np.linspace(0 , 50 , 20)
print("==> " , c)  # Output: An array of 20 evenly spaced values from 0 to 50.

array2 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,8,7,5]])

print("Memory address ==> " , array2.data)  # Output: Will vary.

print("Number of elements ==> " , array2.size)  # Output: Number of elements ==>  12

print("1D array version ==> " , array2.ravel())  # Output: 1D array version ==>  [1 2 3 4 5 6 7 8 9 8 7 5]

(15,)
shape => (3, 5)
Dimension => 2
Data type => int64
Size =>  15
type =>  <class 'numpy.ndarray'>
[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.          2.63157895  5.26315789  7.89473684]
 [10.52631579 13.15789474 15.78947368 18.42105263]
 [21.05263158 23.68421053 26.31578947 28.94736842]
 [31.57894737 34.21052632 36.84210526 39.47368421]
 [42.10526316 44.73684211 47.36842105 50.        ]]
==>  [ 0 12 24 36 48 60 72 84]
==>  [ 0.          2.63157895  5.26315789  7.89473684 10.52631579 13.15789474
 15.78947368 18.42105263 21.05263158 23.68421053 26.31578947 28.94736842
 31.57894737 34.21052632 36.84210526 39.47368421 42.10526316 44.73684211
 47.36842105 50.        ]
Memory address ==>  <memory at 0x78d60d65a5a0>
Number of elements ==>  12
1D array version ==>  [1 2 3 4 5 6 7 8 9 8 7 5]


**5 ) NumPy - NumPy Basics Operations**

This section focuses on mathematical operations, trigonometric functions, comparisons, and array operations in NumPy. It explains how these operations can be performed with examples.

In [26]:
import numpy as np
from numpy import * 

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)  # Output: [5 7 9]

print(a-b)  # Output: [-3 -3 -3]

print(a**2)  # Output: [1 4 9]

print(np.sin(a))  # Output: [0.84147098 0.90929743 0.14112001]

print(a < 2)  # Output: [ True False False]

aa = np.array([[1,2,3],
               [4,5,6]])

bb = np.array([[1,2,3],
               [4,5,6]])

print("a x b ==> " , a*b)  # Output: a x b ==>  [ 4 10 18]

# print(aa.dot(bb))  # Will result in an error as the number of rows in aa must be equal to the number of columns in bb.

print("==> \n" , aa.dot(bb.T))  # Output: [[14 32]
                                #          [32 77]]

aaa = np.random.random((5,5))  # Generates a 5x5 array of random numbers between 0 and 1.
print("Random 5x5 ==> " , aaa)

print("Sum of all elements in the array ==> " , aaa.sum())
print("Maximum value in the array ==> " , aaa.max())
print("Minimum value in the array ==> " , aaa.min())

print("Sum of columns ==> " , aaa.sum(axis=0))
print("Sum of rows ==> " , aaa.sum(axis=1))

print("Square root of the matrix ==> " , np.sqrt(aaa))
print("Square of the matrix ==> " , np.square(aaa))  # Equivalent to aaa**2
print("Sum of two matrices ==> " , np.add(aaa , aaa))

[5 7 9]
[-3 -3 -3]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[ True False False]
a x b ==>  [ 4 10 18]
==> 
 [[14 32]
 [32 77]]
Random 5x5 ==>  [[0.47463262 0.22728313 0.52086397 0.74239026 0.42989246]
 [0.70029828 0.84336884 0.90245075 0.35750923 0.04539756]
 [0.45884525 0.58555311 0.77782108 0.35106282 0.69774308]
 [0.80547478 0.86848055 0.47864483 0.81482615 0.67575214]
 [0.12586162 0.43002699 0.65348162 0.86110488 0.43306732]]
Sum of all elements in the array ==>  14.261833313175114
Maximum value in the array ==>  0.902450754023786
Minimum value in the array ==>  0.045397555848918136
Sum of columns ==>  [2.56511256 2.95471262 3.33326225 3.12689333 2.28185255]
Sum of rows ==>  [2.39506244 2.84902465 2.87102535 3.64317844 2.50354243]
Square root of the matrix ==>  [[0.68893586 0.47674221 0.72170906 0.86162072 0.65566185]
 [0.83683827 0.91835115 0.94997408 0.59792075 0.21306702]
 [0.67738117 0.76521442 0.88194165 0.59250555 0.83531017]
 [0.89748247 0.93192304 0.69184162 0.90267721 0.

Note: The "Output:" sections have not been included here due to their length and complexity.
For detailed information, you can visit https://github.com/Enes-berke

**6 ) NumPy - Index Selection** 

This section focuses on how to access specific elements and slices of arrays. It provides practical examples of indexing and slicing operations.

In [27]:
import numpy as np
from numpy import *

a = np.random.randint(7 , 23, 10) # Creates an array of 10 elements between 7 and 23.

print("a ==> " , a)
# Output:
# a ==>  [20 14 18 16 12 15 22 22 12 11]

print("a[0] ==>" , a[0])
# Output:
# a[0] ==> 20

print("a[0:5] ==>" , a[0:5]) 
# Output:
# a[0:5] ==> [20 14 18 16 12]

a[0] = 999 # Sets the value at index 0 to 999.

print("a ==> " , a)
# Output:
# a ==>  [999  14  18  16  12  15  22  22  12  11]

m = np.random.randint(12 , 55 , (3 , 5)) 
# Creates a 3x5 array (matrix) with random values between 12 and 55.

print("\n\n m[] ==>" , m)
# Output: Will display the 3x5 matrix.

print("\nm[0, 0] ==>" , m[0, 0]) # Row = 0 / Column = 0
# Output:
# m[0, 0] ==> 31

print("\nm[1, 1]" , m[1, 1]) # Row = 1 / Column = 1
# Output:
# m[1, 1] = 50

print("\nm[2, 3] ==>" ,m[2, 3]) # Row = 2 / Column = 3
# Output:
# m[2, 3] ==> 31

print("\nm[2, 3] ==>" ,m[2, 3]) # Value has been changed.
# Output:
# m[2, 3] = 999

print("\nm[:, 0] ==>" ,m[:, 0]) 
# Row = from 0 to last row / Column = 0
# Will display the elements in the first column for all rows.
# Output: m[:, 0] ==> [31 47 31]

print("\nm[1, :] ==> " , m[1, :]) 
# Row = 1 / Column = from 0 to last column
# Will display all elements in the second row.
# Output: m[1, :] ==>  [47 50 43 44 24]

print("\nm[0:2, 0:3] ==> " , m[0:2, 0:3]) 
# Rows = 0 - 1 / Columns = 0 - 1 - 2
# Will display a 2x3 sub-matrix.
# Output: m[0:2, 0:3] ==>  [[31 21 23]
#                           [47 50 43]]

a ==>  [20 11 17 12 15 18 22 22 17 20]
a[0] ==> 20
a[0:5] ==> [20 11 17 12 15]
a ==>  [999  11  17  12  15  18  22  22  17  20]


 m[] ==> [[20 52 18 30 51]
 [22 35 30 19 40]
 [45 47 22 15 22]]

m[0, 0] ==> 20

m[1, 1] 35

m[2, 3] ==> 15

m[2, 3] ==> 15

m[:, 0] ==> [20 22 45]

m[1, :] ==>  [22 35 30 19 40]

m[0:2, 0:3] ==>  [[20 52 18]
 [22 35 30]]


**7 ) NumPy - Fancy Indexing**

This section covers how to access specific elements of arrays using the Fancy Indexing method. It provides information on the usage and advantages of Fancy Indexing.

In [28]:
import numpy as np
from numpy import *

v = np.arange(0, 40, 5) 
# Print multiples of 5 from 0 to 40 (excluding 40): 0-5-10-15-20-25-30-35 

print(v)
# Output:
# [ 0  5 10 15 20 25 30 35]

print(v[1])
# Output:
# 5

print(v[4]) 
# Using indices in this way can be cumbersome, so we use the method below instead:
# ==>
# Output:
# 20

index = [1, 2, 3] 

print(v[index])
# Output: 
# [ 5 10 15]

# Using v[index] is a more convenient way to express v[1] - v[2] - v[3].
# It provides a clearer representation of the numbers at indices 1, 2, and 3.

[ 0  5 10 15 20 25 30 35]
5
20
[ 5 10 15]


**8 ) NumPy - Stacking Arrays (Array Concatenation)**

This section provides information about concatenating different arrays, focusing on both vertical and horizontal concatenation operations. Practical examples are used to demonstrate how these operations are performed.

In [29]:
import numpy as np
from numpy import *

array1 = np.array([[1,2],[3,4]])
array2 = np.array([[-1,-2],[-3,-4]])

# Vertical concatenation
# array([[1, 2],
#        [3, 4]])
# array([[-1, -2],
#        [-3, -4]])
array3 = np.vstack((array1,array2))
print(array3)
# Output:
# [[ 1  2]
#  [ 3  4]
#  [-1 -2]
#  [-3 -4]]

# Horizontal concatenation
# array([[1, 2],[-1, -2],
#        [3, 4]],[-3, -4]]
array4 = np.hstack((array1,array2))
print(array4)
# Output:
# [[ 1  2 -1 -2]
#  [ 3  4 -3 -4]]

[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
[[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


**9) NumPy - Splitting Arrays**

This section focuses on the operation of cutting and splitting arrays at specific points. It explains the usage of the split function with examples.

In [30]:
import numpy as np
from numpy import * 

x = np.array([1,2,3,4,5,99,88,77,6,7,8,9])

print ( np.split ( x , [ 5 , 8 ] ) )
# Output:
# [array([1, 2, 3, 4, 5]), array([99, 88, 77]), array([6, 7, 8, 9])]

a , b , c =  np.split ( x , [ 5 , 8 ] ) 

print("\n a ==> " , a)
# Output: 
# a ==>  [1 2 3 4 5]

print("\n b ==> " , b)
# Output: 
# b ==>  [99 88 77]

print("\n c ==> " , c)
# Output: 
# c ==>  [6 7 8 9]

[array([1, 2, 3, 4, 5]), array([99, 88, 77]), array([6, 7, 8, 9])]

 a ==>  [1 2 3 4 5]

 b ==>  [99 88 77]

 c ==>  [6 7 8 9]


**10 ) NumPy - Convert and Copy**

This section provides information about converting arrays to different data types and copying operations. It covers important considerations and provides examples.

In [31]:
import numpy as np
from numpy import *

liste = [1,2,3,4]   # list

array = np.array(liste) # Convert to array

liste2 = list(array) # Convert to list

a = np.array([1,2,3])

b = a
print("before b ==>", b)
# Output:
# before b ==> [1 2 3]

b[0] = 5 
# This operation changes the value in the 'a' array as well. 
# 'a', 'b', and 'c' are allocated the same memory space.
# Therefore, any changes will affect all of them. 

c = a

print(" a ==>", a)
# Output: 
# a ==> [5 2 3]

print("late b ==>", b)
# Output:
# late b ==> [5 2 3]

print(" c ==>", c)
# Output: 
# c ==> [5 2 3]

d =  np.array([1,2,3])
print(" d ==>", d)
# Output: 
# d ==> [1 2 3]

e = d.copy()
print(" e ==>", e)
# Output:
# e ==> [1 2 3]

f = d.copy()
print(" f ==>", f)
# Output: 
# f ==> [1 2 3]

before b ==> [1 2 3]
 a ==> [5 2 3]
late b ==> [5 2 3]
 c ==> [5 2 3]
 d ==> [1 2 3]
 e ==> [1 2 3]
 f ==> [1 2 3]


**11 ) NumPy - Conditions on Numpy**

This section provides information about the importance of performing conditional operations on arrays and demonstrates how to do it with examples.

In [32]:
import numpy as np
from numpy import *

a = np.array([1,2,3,4,5,6,7,8,9,11,22,33,44,55,66,77,88,99,100])

# Print values greater than 30 in our vector

print("Values greater than 30 ==> " , a[a>30] )
# Output:
# Values greater than 30 ==>  [ 33  44  55  66  77  88  99 100]

print("Values less than 30 ==> " , a[a < 30] )
# Output:
# Values less than 30 ==>  [ 1  2  3  4  5  6  7  8  9 11 22]

print("Values not equal to 33 ==> " , a[a != 33] )
# Output:
# Values not equal to 33 ==>  
# [  1   2   3   4   5   6   7   8   9  11  22  44  55  66  77  88  99 100]

print("Values equal to 22 ==> " , a[a == 22] )
# Output:
# Values equal to 22 ==>  [22]

print("Values equal to or greater than 33 ==> " , a[a >= 33] )
# Output:
# Values equal to or greater than 33 ==>  [ 33  44  55  66  77  88  99 100]

Values greater than 30 ==>  [ 33  44  55  66  77  88  99 100]
Values less than 30 ==>  [ 1  2  3  4  5  6  7  8  9 11 22]
Values not equal to 33 ==>  [  1   2   3   4   5   6   7   8   9  11  22  44  55  66  77  88  99 100]
Values equal to 22 ==>  [22]
Values equal to or greater than 33 ==>  [ 33  44  55  66  77  88  99 100]
